name: Deploy Frontend Dev

on:
  push:
    branches:
      - dev
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code manually
        run: |
          git clone --branch ${{ github.ref_name }} --single-branch http://109.122.249.153/mercurail/inshop-app.git .

      - name: Build image
        run: docker build -t registry:5000/frontend:dev .

      - name: Push image
        run: docker push registry:5000/frontend:dev

      - name: Deploy service
        run: docker service update --image registry:5000/frontend:dev inshop_frontend-dev