name: Deploy Frontend Dev

on:
  push:
    branches:
      - dev
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code manually
        run: |
          git clone http://git.inshop.internal/mercurail/checkout.git .
          git checkout dev

      - name: Build image
        run: docker build -t registry:5000/frontend:dev .

      - name: Push image
        run: docker push registry:5000/frontend:dev

      - name: Deploy service
        run: docker service update --image registry:5000/frontend:dev inshop_frontend-dev